### ISSUE TITLE
Last Updated on package page not updating

### ISSUE THREAD

**Issue by jhsolomon** [k-int/gokb-phase1#583] opened 2017-01-10 14:21 UTC
Is this related to #579?

The Last Updated field is not updating on the package record either.
http://gokb.openlibraryfoundation.org/gokb/resource/show/org.gokb.cred.Package%3A274092

![image](https://cloud.githubusercontent.com/assets/13369381/21809534/30a0c8cc-d716-11e6-8b5b-2ef18e1857d3.png)

**Comment by sosguthorpe** [comment] 2017-01-10 14:29
Closing as duplicate of #579.
#580 Already closed for this reason too.

**Closed as completed by sosguthorpe** 2017-01-10 14:29 UTC
Labels: 7.0.13
