### ISSUE TITLE
Registering new user - error encountered

### ISSUE THREAD

**Issue by iamcreative** [k-int/gokb-phase1#84] opened 2013-12-06 10:09 UTC
I encountered an error a couple of days ago when trying to register myself as a user which resulted in a blank screen and no error message - I put it down to the fact that I might already have registered for an account and in the interests of making progress with testing I just went back to using the Admin account.

I've just had another go at registering, this time with my personal email account and it's thrown an error with a message this time:
"HTTP Status 500 - Error applying layout : main

type Exception report

message Error applying layout : main

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error applying layout : main
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:744)
root cause

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Cannot get property 'mainMenuSections' on null object
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:744)
root cause

java.lang.NullPointerException: Cannot get property 'mainMenuSections' on null object
    gsp_gokb_layoutsmain_gsp$_run_closure2.doCall(gsp_gokb_layoutsmain_gsp.groovy:47)
    gsp_gokb_layoutsmain_gsp.run(gsp_gokb_layoutsmain_gsp.groovy:174)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:744)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.42 logs."

**Comment by ianibo** [comment] 2013-12-08 12:49
Fixed in dev branch (Needs test) caused by new menu functionality leaking into post-signup page.

**Closed as completed** 2014-08-06 13:19 UTC

**Comment by iamcreative** [comment] 2014-08-06 13:24
Tested and confirmed as fixed on https://test-gokb.kuali.org/
