### ISSUE TITLE
Fix formatting on license display

### ISSUE THREAD

**Issue by kristenwilson** [k-int/gokb-phase1#106] opened 2014-04-24 20:17 UTC
The license record display has a bunch of question marks floating around on the page. You can click on them and additional text appears. Should these be buttons? (Spreadsheet ref no. 23)

**Comment by sosguthorpe** [comment] 2014-08-04 15:20
Have changed the cursor to become a pointer but they shouldn't be buttons I don't think.

**Comment by sosguthorpe** [comment] 2015-02-02 13:35
Duplicate of #222

**Closed as completed by sosguthorpe** 2015-02-02 13:35 UTC
